# Generated by Django 5.2.7 on 2025-11-02 20:25

import django.db.models.deletion
import hair_transformation.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HairTransformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to=hair_transformation.models.user_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('skin_tone', models.CharField(blank=True, max_length=50)),
                ('ethnicity', models.CharField(blank=True, max_length=100)),
                ('face_shape', models.CharField(blank=True, max_length=50)),
                ('hair_length', models.CharField(blank=True, max_length=50)),
                ('hair_texture', models.CharField(blank=True, max_length=50)),
                ('style_recommendations', models.JSONField(default=list)),
                ('color_recommendations', models.JSONField(default=list)),
                ('hair_analysis_image', models.ImageField(blank=True, null=True, upload_to=hair_transformation.models.result_upload_path)),
                ('face_analysis_image', models.ImageField(blank=True, null=True, upload_to=hair_transformation.models.result_upload_path)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransformationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=200)),
                ('style_type', models.CharField(max_length=50)),
                ('transformed_image', models.ImageField(upload_to=hair_transformation.models.result_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hair_transformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='hair_transformation.hairtransformation')),
            ],
            options={
                'ordering': ['style_type', 'style_name'],
            },
        ),
    ]
